"""payment_architecture

Revision ID: 1f3091d404ab
Revises: b6fdf8b17ad4
Create Date: 2026-07-26 15:30:50.026913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f3091d404ab'
down_revision: Union[str, None] = 'b6fdf8b17ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('credit_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('merchant_credit_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('credit_plan_id', sa.UUID(), nullable=False),
    sa.Column('amount_paid', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('credit_received', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'failed', name='merchant_credit_order_status'), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('provider_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('initiated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['credit_plan_id'], ['credit_plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_reference')
    )
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('merchant_credit_order_id', sa.UUID(), nullable=True),
    sa.Column('type', postgresql.ENUM('purchase', 'deduction', 'trial', 'adjustment', name='credit_transaction_type'), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'reversed', name='credit_transaction_status'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('direction', postgresql.ENUM('CREDIT', 'DEBIT', name='credit_transaction_direction'), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_credit_order_id'], ['merchant_credit_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # Create enums before adding columns that depend on them
    payment_model = postgresql.ENUM('credit', 'pay_as_you_go', name='payment_model')
    payment_model.create(op.get_bind(), checkfirst=True)

    channel_type = postgresql.ENUM('paybill', 'till', 'bank', name='channel_type')
    channel_type.create(op.get_bind(), checkfirst=True)

    op.add_column('businesses', sa.Column('payment_model', postgresql.ENUM('credit', 'pay_as_you_go', name='payment_model'), nullable=False, server_default='pay_as_you_go'))
    op.add_column('businesses', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.add_column('businesses', sa.Column('channel_type', postgresql.ENUM('paybill', 'till', 'bank', name='channel_type'), nullable=True))
    op.add_column('businesses', sa.Column('channel_account', sa.String(length=50), nullable=True))
    op.add_column('businesses', sa.Column('credit_balance', sa.DECIMAL(precision=12, scale=2), nullable=False, server_default='0'))
    op.alter_column('businesses', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('businesses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('businesses', 'trust_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('80'))
    op.alter_column('categories', 'requires_deposit',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('customer_contact_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'trust_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('delivery_assignments', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('delivery_assignments', 'rider_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('delivery_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('delivery_assignments', 'status',
               existing_type=postgresql.ENUM('assigned', 'unassigned', name='assignment_status'),
               nullable=False,
               existing_server_default=sa.text("'assigned'::assignment_status"))
    op.alter_column('delivery_attempts', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('delivery_attempts', 'attempt_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('delivery_attempts', 'evidence_required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index('idx_delivery_attempts_gps_point', 'delivery_attempts', ['gps_point'], unique=False, postgresql_using='gist')
    op.alter_column('disputes', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('disputes', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('disputes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ledger_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('locations', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('locations', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'sent'::character varying"))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('operating_hours', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('operating_hours', 'day_of_week',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('operating_hours', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('order_items', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('orders', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('orders', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('orders', 'requires_deposit',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_orders_delivery_coordinates', 'orders', ['delivery_coordinates'], unique=False, postgresql_using='gist')
    op.alter_column('payment_attempts', 'payment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('payment_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_methods', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('payment_methods', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('payment_methods', 'effective_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('payments', sa.Column('payment_model', postgresql.ENUM('credit', 'pay_as_you_go', name='payment_model'), nullable=False, server_default='pay_as_you_go'))
    op.add_column('payments', sa.Column('initiated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('payments', sa.Column('completed_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('payments', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('pending', 'verified', 'failed', name='payment_status'),
               nullable=False,
               existing_server_default=sa.text("'pending'::payment_status"))
    op.alter_column('products', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('products', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('riders', 'business_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('riders', 'status',
               existing_type=postgresql.ENUM('pending', 'active', 'inactive', name='rider_status'),
               nullable=False,
               existing_server_default=sa.text("'pending'::rider_status"))
    op.alter_column('settlements', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='settlement_status'),
               nullable=False,
               existing_server_default=sa.text("'pending'::settlement_status"))
    op.alter_column('settlements', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('trust_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trust_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('settlements', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('settlements', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='settlement_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::settlement_status"))
    op.alter_column('riders', 'status',
               existing_type=postgresql.ENUM('pending', 'active', 'inactive', name='rider_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::rider_status"))
    op.alter_column('riders', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('products', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('payments', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('pending', 'verified', 'failed', name='payment_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::payment_status"))
    op.alter_column('payments', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('payment_methods', 'effective_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_methods', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('payment_methods', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('payment_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_attempts', 'payment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_orders_delivery_coordinates', table_name='orders', postgresql_using='gist')
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'requires_deposit',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('orders', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('orders', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('operating_hours', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('operating_hours', 'day_of_week',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('operating_hours', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'sent'::character varying"))
    op.alter_column('locations', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('locations', 'business_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ledger_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('disputes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('disputes', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('disputes', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_delivery_attempts_gps_point', table_name='delivery_attempts', postgresql_using='gist')
    op.alter_column('delivery_attempts', 'evidence_required',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('delivery_attempts', 'attempt_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('delivery_attempts', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('delivery_assignments', 'status',
               existing_type=postgresql.ENUM('assigned', 'unassigned', name='assignment_status'),
               nullable=True,
               existing_server_default=sa.text("'assigned'::assignment_status"))
    op.alter_column('delivery_assignments', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('delivery_assignments', 'rider_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('delivery_assignments', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('customers', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('customers', 'trust_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('customer_contact_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'requires_deposit',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('businesses', 'trust_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('80'))
    op.alter_column('businesses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('businesses', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('product_images',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('image_data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('"position" >= 1 AND "position" <= 3', name='ck_product_image_position'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_images_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='product_images_pkey'),
    sa.UniqueConstraint('product_id', 'position', name='uq_product_image_position')
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.create_table('delivery_evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('delivery_attempt_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('image_data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['delivery_attempt_id'], ['delivery_attempts.id'], name='delivery_evidence_delivery_attempt_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='delivery_evidence_pkey')
    )
    # ### end Alembic commands ###
